cursor #ebe0dd
cursor_text_color #d6c3bb

foreground            #ebe0dd
background            #171211
selection_foreground  #402c23
selection_background  #e0c0b2
url_color             #fcbea3

color0   #171211
color1   #ff7772
color2   #95fc7e
color3   #ffe572
color4   #efa889
color5   #744029
color6   #fcbea3
color7   #fff4ef
color8   #a39b97
color9   #ffa29f
color10  #b6ffa5
color11  #ffeea5
color12  #ffc9b2
color13  #ffd3bf
color14  #ffe2d6
color15  #fffaf8
